-- AlterTable
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "instrumentName" TEXT;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "optionType" TEXT;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "strike" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "expiry" TIMESTAMP(3);
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "daysToExpiry" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumUsd" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumCoin" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "markIv" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumEntryLow" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumEntryHigh" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumTarget1" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumTarget2" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "premiumStopLoss" DOUBLE PRECISION;
ALTER TABLE "Signal" ADD COLUMN IF NOT EXISTS "optionMeta" JSONB;
