-- AlterTable
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "dailyLossLimitInr" DOUBLE PRECISION NOT NULL DEFAULT 2000;
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "maxConsecutiveStopLosses" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "maxSpreadPct" DOUBLE PRECISION NOT NULL DEFAULT 0.08;
ALTER TABLE "BotConfig" ADD COLUMN IF NOT EXISTS "minOpenInterest" DOUBLE PRECISION NOT NULL DEFAULT 10;
